### ISSUE TITLE
Price is undefined, Estimated Wait Time undefined minutes

### ISSUE THREAD

**Issue by domainzero** [bhberson/pizzadash#12]
Can't seem to get my order to actually go through, order validates but doesn't actually submit.
Below is what gets returned when I submit my order.

```
sudo node app.js
single element detected
Dash Button Found
[ { AutoRemove: false,
    Code: '9193',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  { AutoRemove: false,
    Code: '12SCREEN',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  { AutoRemove: false,
    Code: 'PINPASCA',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  [length]: 3 ]
Order is Priced
[ { AutoRemove: false,
    Code: '9193',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  { AutoRemove: false,
    Code: '12SCREEN',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  { AutoRemove: false,
    Code: 'PINPASCA',
    Qty: 1,
    ID: 1,
    isNew: true,
    Options: { C: { '1/1': '1' }, X: { '1/1': '1' } } },
  [length]: 3 ]
Order is Validated
Price is undefined
Estimated Wait Time undefined minutes
```

and here's what my order looks like.

```
order.addItem(
    new pizzapi.Item(
        {
           code: '9193',
           options: {},
           quantity: 1
        }
    )
);
order.addItem(
    new pizzapi.Item(
        {
            code: '12SCREEN',
            options: {S: [Object], P: [Object]},
            quantity: 1
        }
    )
);
order.addItem(
    new pizzapi.Item(
        {
           code: 'PINPASCA',
           options: {},
           quantity: 1
        }
        )
);
```

Am I missing something? I've tried to fiddle with this without the coupon, without topping options, and even with a single menu item and I keep getting the same results.

This is on an raspberry pi running debian if it matters at all.

**Comment by mynamebrody** [comment]
I haven't made an actual order in quite some time. Let me look into this over the next week or so.

**Comment by JoeIaquinto** [comment]
I think there may be flaws in the dominos api. We tested it out fully on Friday but we kept getting invalid statuses from our calls to order and validate. We believe there's something wrong with the way we or the dominos api make the order object. Because the documentation is very lackluster on Dominos's end, I've been looking into using their Twitter easy ordering feature to order with the dash button. We could make a static tweet to @dominos when the user presses a button, and use a website for the Twitter app connection to pizzadash and redirecting users that haven't yet setup Dominos Tweet-to-order to their website. This would allow users to use the Dominos website for order entry, allow them to get rewards points, get deals and coupons, and increase security by keeping user info in the hands of Dominos.

**Comment by mynamebrody** [comment]
@JoeIaquinto if you guys pursue this, I would recommend you creating your own repo as that would change the behavior of what this repo is doing. I have not tested this application in months (really since I made the video), but as this is a different idea of how it's implemented and intended to be used, I would not accept any pull requests with this method.

**Comment by JoeIaquinto** [comment]
Completely understandable. We present our project Tomorrow so there's not enough time for us to pivot to using Twitter anyways right now. I was looking at Dominos.com last night and inspecting the API requests and responses via Chrome dev tools XHR request monitoring and I had the idea to run a proxy to intercept the outgoing requests from a user on Dominos website so that it can be repeated by the Dash button on each press. We may try to build a fork around this idea and see where it goes. I know https://github.com/maddox/dasher already exists so maybe we'll be able to use that. I really wish dominos better supported their API so that it was easier to place orders without directly using their website or apps, I think it would benefit their "AnyWare" campaign.

**Comment by JoeIaquinto** [comment]
@domainzero You might want to look at the node-dominos-api more. I believe the order to call the functions is validate, price, place. It would help to post the full response in the callback from when you press the button. Dominos sends back a Status and StatusItems  which give more detail on why the call was rejected (The data is formatted incorrectly, the POS system failed to process the credit card, the store is closed). You may see PriceInformationRemoved as a status item, but it's just a warning and won't prevent an order.

**Comment by JoeIaquinto** [comment]
Also, I placed an order last night and today in class successfully! I'll work on figuring out which of my changes are needed to update the master branch to a more usable version right out of the box. I want to figure out how to get Customer IDs, Easy-Order IDs, and Saved card IDs so that the user can find theirs and set it. I copied the payload from my validate, price, and place order requests on Dominos.com and used them to find what is lacking in node-dominos-api so right now my version is a bit hacky,
